# Generated by Django 5.2.4 on 2025-07-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscal',
            name='data_emissao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
