# Generated by Django 5.2.4 on 2025-07-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0003_alter_notafiscal_data_emissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='blockchain_tx',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='conteudo',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='numero',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
